name: Deploy to GitHub Pages

on:
  push:
    branches:
      - live  # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python3.x-dev
        run: sudo apt-get install -y python3-dev  # Replace x with the specific version

      - name: Create venv
        run: python -m venv venv

      - name: Activate venv
        run: |
          source venv/bin/activate

      - name: Install system dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y python3-dev python3-pip python3-setuptools
            sudo apt-get install -y build-essential libatlas-base-dev
  
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
  
      - name: Install numpy
        run: pip install numpy==1.19.3

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r .github/workflows/requirements.txt

      - name: Build Flask app
        run: |
          python app.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
