name: Deploy to GitHub Pages

on:
  push:
    branches:
      - live  # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python3.x-dev
        run: sudo apt-get install -y python3.x-dev  # Replace x with the specific version

      - name: Create venv
        run: python -m venv venv

      - name: Activate venv and install/updgrade pip
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r .github/workflows/requirements.txt

      - name: Build Flask app
        run: |
          python app.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
